### ISSUE TITLE
Make the event trigger at the event capture stage

### ISSUE THREAD

**Issue by YogiWu** [vue-bulma/click-outside#16]
I noticed that the handle function is triggered at the event bubble stage.However, it would not be triggered when the click event handle by the function with 'event.stopPropagation()'.So, I think trigger the handle at the event capture will be better.

**Comment by WORMSS** [comment]
Could always add a modifier so it becomes 
```
v-click-outside.capture="hide"
```

**Comment by YogiWu** [comment]
I may try it again, thank you

**Comment by WORMSS** [comment]
https://github.com/vue-bulma/click-outside/pull/10
