### ISSUE TITLE
`update` method prevents unbinding

### ISSUE THREAD

**Issue by JTallis** [vue-bulma/click-outside#4]
I was facing an issue where if any sort of data changed, it would trigger the update method of the directive.

Navigating away from the page and subsequent clicks would still fire the click event and then error. The click event wasn't unset.

I tried to figure out why. When the handler is set `el.__vueClickOutside__` will contain something like `handler(e)` which is great. That's what we want to see. The value of `el.__vueClickOutside__` was `boundFn(a)` inside of the unbind method which is the reason why it would not unbind the event. I checked `binding.value` within the update method to see that it is the update method that is setting `el.__vueClickOutside__` to `boundFn(a)`. This leaves me to believe the update method sets a "clone" of the handler and there for not being unset as the original binding is a different function.

It would be great if someone could duplicate this issue. The steps are simple.

Have an element that uses `vue-click-outside` and make sure your data changes which causes the view to update. Navigate away from the page (I use `vue-router` so I don't refresh the app) and it will be fine. This is because it was handled. Click anywhere on the page or navigate to another and so on, will result in an error as follows:

```
Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at isPopup (app.js:8421)
    at HTMLDocument.handler (app.js:8442)
```

This is because the node in question no longer exists but the event is still set. Hopefully I made sense.

**Comment by JTallis** [comment]
I've looked up other click outside handlers and they omit the update method. Is there any purpose to the update method?

**Comment by luventa** [comment]
I think I made a mistake in `update` function. Will try to fix this.
Thanks!
