### ISSUE TITLE
SSR not supported

### ISSUE THREAD

**Issue by wilk** [vue-bulma/click-outside#5]
Missing support for Server Side Rendering: invoking `document.addEventListener('click', handler)` doesn't work at server-side.

**Comment by luventa** [comment]
I will add SSR check for click-outside soon.
Thanks for reporting this.

**Comment by luventa** [comment]
hi @wilk , I just published new version for this component.
SSR error is avoid. But I'm not sure if it still works on Server side render.
I've checked Vue's docs and found out that they might want to provide API of `document` for SSR. But it seems not support events yet. [Head Management](https://ssr.vuejs.org/en/head.html)

Will make this support SSR once they provide the functionality. 😄
