### ISSUE TITLE
npmjs vs github repo

### ISSUE THREAD

**Issue by NelinD** [vue-bulma/click-outside#7]
source code npmjs !== source code githab repo

**Comment by inanimatt** [comment]
Thanks for this directive - very handy! Unfortunately I'm suffering from the "Cannot read property $isServer of undefined" error that I can see is fixed in `master`, so I'd really appreciate if you could release a new version on NPM.

**Comment by jabadia** [comment]
+1

**Comment by EugeneBalabai** [comment]
please new version for npm

**Comment by luventa** [comment]
just published. Sorry for the inconvenience.
