### ISSUE TITLE
TypeError: Cannot read property '$isServer' of undefined

### ISSUE THREAD

**Issue by altpoint** [vue-bulma/click-outside#8]
```
[Vue warn]: Error in directive click-outside bind hook: "TypeError: Cannot read property '$isServer' of undefined"
```
version 1.0.6

**Comment by skyrpex** [comment]
Not sure if it's still happening, but [this line](https://github.com/vue-bulma/click-outside/blob/master/index.js#L31) would be safer (and shorter) if we change the condition to:

```js
return vNode.componentInstance && vNode.componentInstance.$isServer
```

**Comment by weizs** [comment]
The code is different from github at npm

**Comment by freearhey** [comment]
Please update npm package

**Comment by Sean-Der** [comment]
Hey @luventa is there anything I can do to help get a new version published to npm?

thanks

**Comment by ymatuhin** [comment]
Until it's not published in npm, you can use `npm install https://github.com/vue-bulma/click-outside.git`. It's worked for me.

**Comment by luventa** [comment]
1.0.7 published.
